# .github/workflows/vue-ci.yml

name: Vue.js CI/CD # Cambié el nombre para reflejar que ahora hace CI y CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  build_and_test_vue:
    name: Build and Test Vue App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Simplificado a una versión, puedes usar [18.x, 20.x] si prefieres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Lint code
      #   run: npm run lint

      - name: Build Vue application
        run: npm run build # Esto crea la carpeta 'dist'

      - name: List contents of dist directory # Para depurar y ver qué se construyó
        run: ls -R ./dist || echo "Directorio dist no encontrado o vacío"

      # --- PASO FALTANTE AÑADIDO AQUÍ ---
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist-artifact # El nombre DEBE COINCIDIR con el que usa el job de deploy
          path: ./dist # Sube el contenido de la carpeta 'dist'
      # --- FIN DEL PASO AÑADIDO ---

  deploy_vue_to_ec2:
    name: Deploy Vue App to EC2
    needs: build_and_test_vue
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vue-dist-artifact # Nombre del artefacto a descargar
          path: ./dist # Descarga el contenido del artefacto a una carpeta 'dist' en el workspace

      - name: Display structure of downloaded dist folder # Modificado para ser más específico
        run: ls -R ./dist || echo "Directorio dist descargado no encontrado o vacío"

      - name: Prepare remote directory on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Preparing remote directory ${{ secrets.VUE_REMOTE_APP_DIR }}"
            sudo mkdir -p ${{ secrets.VUE_REMOTE_APP_DIR }}
            sudo chown ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} ${{ secrets.VUE_REMOTE_APP_DIR }}
            echo "Cleaning old files from ${{ secrets.VUE_REMOTE_APP_DIR }}"
            if [ -d "${{ secrets.VUE_REMOTE_APP_DIR }}" ]; then
              # Elimina solo archivos y subdirectorios dentro, no el directorio padre
              sudo find ${{ secrets.VUE_REMOTE_APP_DIR }} -mindepth 1 -delete 
            fi
            echo "Remote directory prepared."

      - name: SCP files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          source: './dist/*' # Copia el contenido de la carpeta 'dist' local
          target: '${{ secrets.VUE_REMOTE_APP_DIR }}'

      - name: Verify deployment (optional)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Listing files in ${{ secrets.VUE_REMOTE_APP_DIR }} after deployment:"
            ls -la ${{ secrets.VUE_REMOTE_APP_DIR }}
            echo "Vue app deployment complete."
